import type { Client, Brand, TeamMember, Team, Project } from '@/types';

export const initialClients: Client[] = [
  { id: 'c1', name: 'ПАО Сбербанк' },
  { id: 'c2', name: 'ООО Яндекс' },
  { id: 'c3', name: 'ООО МТС' },
  { id: 'c4', name: 'АО Альфа-Банк' },
];

export const initialBrands: Brand[] = [
  { id: 'b1', name: 'СберМаркет', clientId: 'c1' },
  { id: 'b2', name: 'СберБанк', clientId: 'c1' },
  { id: 'b3', name: 'Яндекс.Маркет', clientId: 'c2' },
  { id: 'b4', name: 'МТС Банк', clientId: 'c3' },
  { id: 'b5', name: 'Альфа-Банк', clientId: 'c4' },
];

export const initialMembers: TeamMember[] = [
  {
    id: 'm1',
    name: 'Иванов Иван Иванович',
    firstName: 'Иван',
    lastName: 'Иванов',
    middleName: 'Иванович',
    email: 'ivanov@example.com',
  },
  {
    id: 'm2',
    name: 'Петрова Анна Сергеевна',
    firstName: 'Анна',
    lastName: 'Петрова',
    middleName: 'Сергеевна',
    email: 'petrova@example.com',
  },
  {
    id: 'm3',
    name: 'Смирнов Петр Александрович',
    firstName: 'Петр',
    lastName: 'Смирнов',
    middleName: 'Александрович',
    email: 'smirnov@example.com',
  },
  {
    id: 'm4',
    name: 'Козлова Елена Дмитриевна',
    firstName: 'Елена',
    lastName: 'Козлова',
    middleName: 'Дмитриевна',
    email: 'kozlova@example.com',
  },
  {
    id: 'm5',
    name: 'Новиков Андрей Викторович',
    firstName: 'Андрей',
    lastName: 'Новиков',
    middleName: 'Викторович',
    email: 'novikov@example.com',
  },
];

export const initialTeams: Team[] = [
  // Сбербанк teams
  {
    id: 'team-c1-shtab',
    name: 'Штаб',
    clientId: 'c1',
    isDefault: true,
    members: [
      { id: 'm1', name: 'Иванов Иван Иванович', firstName: 'Иван', lastName: 'Иванов', middleName: 'Иванович', email: 'ivanov@example.com' },
      { id: 'm2', name: 'Петрова Анна Сергеевна', firstName: 'Анна', lastName: 'Петрова', middleName: 'Сергеевна', email: 'petrova@example.com' },
    ],
  },
  {
    id: 'team-c1-moscow',
    name: 'Команда Москва',
    clientId: 'c1',
    members: [
      { id: 'm3', name: 'Смирнов Петр Александрович', firstName: 'Петр', lastName: 'Смирнов', middleName: 'Александрович', email: 'smirnov@example.com' },
    ],
  },
  {
    id: 'team-c1-regions',
    name: 'Команда Регионы',
    clientId: 'c1',
    members: [
      { id: 'm4', name: 'Козлова Елена Дмитриевна', firstName: 'Елена', lastName: 'Козлова', middleName: 'Дмитриевна', email: 'kozlova@example.com' },
    ],
  },
  {
    id: 'team-c1-federal',
    name: 'Федеральная команда',
    clientId: 'c1',
    members: [
      { id: 'm5', name: 'Новиков Андрей Викторович', firstName: 'Андрей', lastName: 'Новиков', middleName: 'Викторович', email: 'novikov@example.com' },
    ],
  },
  
  // Яндекс teams
  {
    id: 'team-c2-shtab',
    name: 'Штаб',
    clientId: 'c2',
    isDefault: true,
    members: [
      { id: 'm2', name: 'Петрова Анна Сергеевна', firstName: 'Анна', lastName: 'Петрова', middleName: 'Сергеевна', email: 'petrova@example.com' },
      { id: 'm5', name: 'Новиков Андрей Викторович', firstName: 'Андрей', lastName: 'Новиков', middleName: 'Викторович', email: 'novikov@example.com' },
    ],
  },
  {
    id: 'team-c2-digital',
    name: 'Digital команда',
    clientId: 'c2',
    members: [
      { id: 'm3', name: 'Смирнов Петр Александрович', firstName: 'Петр', lastName: 'Смирнов', middleName: 'Александрович', email: 'smirnov@example.com' },
    ],
  },
  {
    id: 'team-c2-tv',
    name: 'ТВ команда',
    clientId: 'c2',
    members: [],
  },
  
  // МТС teams
  {
    id: 'team-c3-shtab',
    name: 'Штаб',
    clientId: 'c3',
    isDefault: true,
    members: [
      { id: 'm1', name: 'Иванов Иван Иванович', firstName: 'Иван', lastName: 'Иванов', middleName: 'Иванович', email: 'ivanov@example.com' },
      { id: 'm2', name: 'Петрова Анна Сергеевна', firstName: 'Анна', lastName: 'Петрова', middleName: 'Сергеевна', email: 'petrova@example.com' },
    ],
  },
  {
    id: 'team-c3-moscow',
    name: 'Команда МТС Москва',
    clientId: 'c3',
    members: [
      { id: 'm3', name: 'Смирнов Петр Александрович', firstName: 'Петр', lastName: 'Смирнов', middleName: 'Александрович', email: 'smirnov@example.com' },
    ],
  },
  {
    id: 'team-c3-regional-tv',
    name: 'Региональная ТВ',
    clientId: 'c3',
    members: [
      { id: 'm5', name: 'Новиков Андрей Викторович', firstName: 'Андрей', lastName: 'Новиков', middleName: 'Викторович', email: 'novikov@example.com' },
    ],
  },
  {
    id: 'team-c3-multi',
    name: 'Мультиканальная команда',
    clientId: 'c3',
    members: [
      { id: 'm4', name: 'Козлова Елена Дмитриевна', firstName: 'Елена', lastName: 'Козлова', middleName: 'Дмитриевна', email: 'kozlova@example.com' },
    ],
  },
  
  // Альфа-Банк teams
  {
    id: 'team-c4-shtab',
    name: 'Штаб',
    clientId: 'c4',
    isDefault: true,
    members: [
      { id: 'm1', name: 'Иванов Иван Иванович', firstName: 'Иван', lastName: 'Иванов', middleName: 'Иванович', email: 'ivanov@example.com' },
    ],
  },
];

// Mock initial projects - полная версия из React проекта
export const initialProjects: Project[] = [
  {
    id: 'p1',
    name: 'Рекламная кампания Осень 2026',
    clientId: 'c1',
    brandId: 'b1',
    settings: {
      period: {
        start: '2026-09-01',
        end: '2026-11-30',
      },
      approvalType: 'Строками',
      amountDisplay: 'С НДС',
      orderParameters: {
        productionAsset: 'Актив 1',
        contractType: 'Основной',
        agencyLegalEntity: 'ООО РА Брусника',
        clientLegalEntity: 'ООО СберМаркет',
        contract: 'Договор №2026/SM-001',
      },
    },
    segments: [
      {
        id: 'seg-1',
        name: 'Москва и МО',
        teamId: 'team-c1-moscow',
        mediaSegments: [
          {
            id: 'ms-1',
            mediaType: 'Outdoor',
            budget: 2500000,
            raDocumentUrl: 'https://docs.google.com/spreadsheets/d/ra-outdoor-1',
            clientDocumentUrl: 'https://docs.google.com/spreadsheets/d/client-outdoor-1',
            summarySheetUrl: 'https://docs.google.com/spreadsheets/d/summary-1',
            orderCode: '#281946',
            launchTasks: [
              { id: 'lt-1', period: 'Январь 2026' },
              { id: 'lt-2', period: 'Февраль 2026' },
              { id: 'lt-3', period: 'Март 2026' },
              { id: 'lt-4', period: 'Апрель 2026' },
              { id: 'lt-5', period: 'Май 2026' },
              { id: 'lt-6', period: 'Июнь 2026' },
              { id: 'lt-7', period: 'Июль 2026' },
              { id: 'lt-8', period: 'Август 2026' },
              { id: 'lt-9', period: 'Сентябрь 2026' },
              { id: 'lt-10', period: 'Октябрь 2026' },
              { id: 'lt-11', period: 'Ноябрь 2026' },
              { id: 'lt-12', period: 'Декабрь 2026' },
            ],
            mediaPlans: [
              {
                id: 'mp-1',
                name: 'План размещения наружной рекламы Q3',
                clientSheetUrl: 'https://docs.google.com/spreadsheets/d/client-mp-1',
                raSheetUrl: 'https://docs.google.com/spreadsheets/d/ra-mp-1',
                statusRA: 'Заказ',
                statusClient: 'Согласовано',
                createdAt: '2026-08-10',
                lastUploadedAt: '2026-08-15',
              },
              {
                id: 'mp-2',
                name: 'Дополнительные площадки',
                clientSheetUrl: 'https://docs.google.com/spreadsheets/d/client-mp-2',
                raSheetUrl: 'https://docs.google.com/spreadsheets/d/ra-mp-2',
                statusRA: 'Заказ',
                statusClient: 'Согласовано',
                createdAt: '2026-08-18',
                lastUploadedAt: '2026-08-20',
                confirmationTaskId: 'ct-2',
              },
            ],
          },
          {
            id: 'ms-2',
            mediaType: 'ТВ',
            budget: 4500000,
            raDocumentUrl: 'https://docs.google.com/spreadsheets/d/ra-tv-1',
            clientDocumentUrl: 'https://docs.google.com/spreadsheets/d/client-tv-1',
            summarySheetUrl: 'https://docs.google.com/spreadsheets/d/summary-2',
            orderCode: '#294851',
            launchTasks: [
              { id: 'lt-3', period: 'Сентябрь 2026' },
            ],
            mediaPlans: [
              {
                id: 'mp-3',
                name: 'ТВ план Первый канал',
                clientSheetUrl: 'https://docs.google.com/spreadsheets/d/client-mp-3',
                raSheetUrl: 'https://docs.google.com/spreadsheets/d/ra-mp-3',
                statusRA: 'Заказ',
                statusClient: 'Согласовано',
                createdAt: '2026-08-05',
                lastUploadedAt: '2026-08-10',
                confirmationTaskId: 'ct-1',
              },
            ],
          },
        ],
      },
      {
        id: 'seg-2',
        name: 'Регионы',
        teamId: 'team-c1-regions',
        mediaSegments: [
          {
            id: 'ms-3',
            mediaType: 'Радио',
            budget: 1200000,
            raDocumentUrl: 'https://docs.google.com/spreadsheets/d/ra-radio-1',
            clientDocumentUrl: 'https://docs.google.com/spreadsheets/d/client-radio-1',
            launchTasks: [],
            mediaPlans: [
              {
                id: 'mp-4',
                name: 'Радио кампания региональные станции',
                clientSheetUrl: 'https://docs.google.com/spreadsheets/d/client-mp-4',
                raSheetUrl: 'https://docs.google.com/spreadsheets/d/ra-mp-4',
                statusRA: 'В работе РА',
                statusClient: '—',
                createdAt: '2026-08-22',
                lastUploadedAt: '2026-08-22',
              },
            ],
          },
        ],
      },
      {
        id: 'seg-status-demo',
        name: 'Демонстрация статусов',
        teamId: 'team-c1-shtab',
        mediaSegments: [
          {
            id: 'ms-status-1',
            mediaType: 'Интернет',
            budget: 3200000,
            raDocumentUrl: 'https://docs.google.com/spreadsheets/d/ra-digital-1',
            clientDocumentUrl: 'https://docs.google.com/spreadsheets/d/client-digital-1',
            launchTasks: [],
            mediaPlans: [
              {
                id: 'mp-status-1',
                name: 'Programmatic кампания Q3',
                clientSheetUrl: 'https://docs.google.com/spreadsheets/d/client-mp-digital-1',
                raSheetUrl: 'https://docs.google.com/spreadsheets/d/ra-mp-digital-1',
                statusRA: 'В работе РА',
                statusClient: 'Согласование',
                createdAt: '2026-09-01',
                lastUploadedAt: '2026-09-05',
              },
            ],
          },
          {
            id: 'ms-status-2',
            mediaType: 'ТВ',
            budget: 5500000,
            raDocumentUrl: 'https://docs.google.com/spreadsheets/d/ra-tv-status-2',
            clientDocumentUrl: 'https://docs.google.com/spreadsheets/d/client-tv-status-2',
            launchTasks: [],
            mediaPlans: [
              {
                id: 'mp-status-2',
                name: 'ТВ размещение федеральные каналы',
                clientSheetUrl: 'https://docs.google.com/spreadsheets/d/client-mp-tv-status-2',
                raSheetUrl: 'https://docs.google.com/spreadsheets/d/ra-mp-tv-status-2',
                statusRA: 'В работе у клиента',
                statusClient: 'Согласование',
                createdAt: '2026-09-02',
                lastUploadedAt: '2026-09-06',
              },
            ],
          },
          {
            id: 'ms-status-3',
            mediaType: 'Outdoor',
            budget: 2800000,
            raDocumentUrl: 'https://docs.google.com/spreadsheets/d/ra-outdoor-status-3',
            clientDocumentUrl: 'https://docs.google.com/spreadsheets/d/client-outdoor-status-3',
            summarySheetUrl: 'https://docs.google.com/spreadsheets/d/summary-outdoor-status-3',
            orderCode: '#382947',
            launchTasks: [
              { id: 'lt-status-3', period: 'Сентябрь 2026' },
            ],
            mediaPlans: [
              {
                id: 'mp-status-3',
                name: 'OOH размещение метро и улицы',
                clientSheetUrl: 'https://docs.google.com/spreadsheets/d/client-mp-outdoor-status-3',
                raSheetUrl: 'https://docs.google.com/spreadsheets/d/ra-mp-outdoor-status-3',
                statusRA: 'Согласовано',
                statusClient: 'Согласовано',
                createdAt: '2026-09-03',
                lastUploadedAt: '2026-09-07',
                confirmationTaskId: 'ct-status-3',
              },
            ],
          },
          {
            id: 'ms-status-4',
            mediaType: 'Радио',
            budget: 1800000,
            raDocumentUrl: 'https://docs.google.com/spreadsheets/d/ra-radio-status-4',
            clientDocumentUrl: 'https://docs.google.com/spreadsheets/d/client-radio-status-4',
            launchTasks: [],
            mediaPlans: [
              {
                id: 'mp-status-4',
                name: 'Радио кампания московские станции',
                clientSheetUrl: 'https://docs.google.com/spreadsheets/d/client-mp-radio-status-4',
                raSheetUrl: 'https://docs.google.com/spreadsheets/d/ra-mp-radio-status-4',
                statusRA: 'На доработку',
                statusClient: 'На доработку',
                createdAt: '2026-09-04',
                lastUploadedAt: '2026-09-08',
              },
            ],
          },
          {
            id: 'ms-status-5',
            mediaType: 'НСТ',
            budget: 2400000,
            raDocumentUrl: 'https://docs.google.com/spreadsheets/d/ra-nst-status-5',
            clientDocumentUrl: 'https://docs.google.com/spreadsheets/d/client-nst-status-5',
            launchTasks: [],
            mediaPlans: [
              {
                id: 'mp-status-5',
                name: 'НСТ размещение торговые центры',
                clientSheetUrl: 'https://docs.google.com/spreadsheets/d/client-mp-nst-status-5',
                raSheetUrl: 'https://docs.google.com/spreadsheets/d/ra-mp-nst-status-5',
                statusRA: 'Отказ',
                statusClient: 'Отказ',
                createdAt: '2026-09-05',
                lastUploadedAt: '2026-09-09',
              },
            ],
          },
          {
            id: 'ms-status-6',
            mediaType: 'Интернет',
            budget: 3500000,
            raDocumentUrl: 'https://docs.google.com/spreadsheets/d/ra-digital-status-6',
            clientDocumentUrl: 'https://docs.google.com/spreadsheets/d/client-digital-status-6',
            summarySheetUrl: 'https://docs.google.com/spreadsheets/d/summary-digital-status-6',
            orderCode: '#394857',
            launchTasks: [
              { id: 'lt-status-6', period: 'Октябрь 2026' },
            ],
            mediaPlans: [
              {
                id: 'mp-status-6',
                name: 'Социальные сети и контекст',
                clientSheetUrl: 'https://docs.google.com/spreadsheets/d/client-mp-digital-status-6',
                raSheetUrl: 'https://docs.google.com/spreadsheets/d/ra-mp-digital-status-6',
                statusRA: 'В работе у клиента',
                statusClient: 'Согласовано',
                createdAt: '2026-09-06',
                lastUploadedAt: '2026-09-10',
                confirmationTaskId: 'ct-status-6',
              },
            ],
          },
          {
            id: 'ms-status-7',
            mediaType: 'ТВ',
            budget: 4200000,
            raDocumentUrl: 'https://docs.google.com/spreadsheets/d/ra-tv-status-7',
            clientDocumentUrl: 'https://docs.google.com/spreadsheets/d/client-tv-status-7',
            launchTasks: [],
            mediaPlans: [
              {
                id: 'mp-status-7',
                name: 'ТВ региональные каналы',
                clientSheetUrl: 'https://docs.google.com/spreadsheets/d/client-mp-tv-status-7',
                raSheetUrl: 'https://docs.google.com/spreadsheets/d/ra-mp-tv-status-7',
                statusRA: 'На доработку',
                statusClient: 'Согласование',
                createdAt: '2026-09-07',
                lastUploadedAt: '2026-09-11',
              },
            ],
          },
          {
            id: 'ms-status-8',
            mediaType: 'Outdoor',
            budget: 2100000,
            raDocumentUrl: 'https://docs.google.com/spreadsheets/d/ra-outdoor-status-8',
            clientDocumentUrl: 'https://docs.google.com/spreadsheets/d/client-outdoor-status-8',
            launchTasks: [],
            mediaPlans: [
              {
                id: 'mp-status-8',
                name: 'OOH размещение аэропорты',
                clientSheetUrl: 'https://docs.google.com/spreadsheets/d/client-mp-outdoor-status-8',
                raSheetUrl: 'https://docs.google.com/spreadsheets/d/ra-mp-outdoor-status-8',
                statusRA: 'Отказ',
                statusClient: '—',
                createdAt: '2026-09-08',
                lastUploadedAt: '2026-09-12',
              },
            ],
          },
          {
            id: 'ms-status-9',
            mediaType: 'Радио',
            budget: 1500000,
            raDocumentUrl: 'https://docs.google.com/spreadsheets/d/ra-radio-status-9',
            clientDocumentUrl: 'https://docs.google.com/spreadsheets/d/client-radio-status-9',
            launchTasks: [],
            mediaPlans: [
              {
                id: 'mp-status-9',
                name: 'Радио региональные станции',
                clientSheetUrl: 'https://docs.google.com/spreadsheets/d/client-mp-radio-status-9',
                raSheetUrl: 'https://docs.google.com/spreadsheets/d/ra-mp-radio-status-9',
                statusRA: 'В работе РА',
                statusClient: 'На доработку',
                createdAt: '2026-09-09',
                lastUploadedAt: '2026-09-13',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'p2',
    name: 'Новогодняя кампания 2026-2027',
    clientId: 'c1',
    brandId: 'b2',
    settings: {
      period: {
        start: '2026-12-01',
        end: '2027-01-15',
      },
      approvalType: 'Документ',
      amountDisplay: 'С НДС',
      orderParameters: {
        productionAsset: 'Актив 2',
        contractType: 'Рамчный',
        agencyLegalEntity: 'ООО РА Брусника',
        clientLegalEntity: 'ПАО Сбербанк',
        contract: 'Договор №2026/SB-045',
      },
    },
    segments: [
      {
        id: 'seg-3',
        name: 'Федеральный охват',
        teamId: 'team-c1-federal',
        mediaSegments: [
          {
            id: 'ms-4',
            mediaType: 'ТВ',
            budget: 8000000,
            raDocumentUrl: 'https://docs.google.com/spreadsheets/d/ra-tv-2',
            clientDocumentUrl: 'https://docs.google.com/spreadsheets/d/client-tv-2',
            launchTasks: [],
            mediaPlans: [
              {
                id: 'mp-5',
                name: 'Новогодний прайм-тайм',
                clientSheetUrl: 'https://docs.google.com/spreadsheets/d/client-mp-5',
                raSheetUrl: 'https://docs.google.com/spreadsheets/d/ra-mp-5',
                statusRA: 'Отказ',
                statusClient: 'Отказ',
                createdAt: '2026-11-01',
                lastUploadedAt: '2026-11-10',
              },
            ],
          },
          {
            id: 'ms-5',
            mediaType: 'Интернет',
            budget: 3500000,
            raDocumentUrl: 'https://docs.google.com/spreadsheets/d/ra-internet-1',
            clientDocumentUrl: 'https://docs.google.com/spreadsheets/d/client-internet-1',
            orderCode: '#472839',
            launchTasks: [],
            mediaPlans: [
              {
                id: 'mp-6',
                name: 'Digital кампания',
                clientSheetUrl: 'https://docs.google.com/spreadsheets/d/client-mp-6',
                raSheetUrl: 'https://docs.google.com/spreadsheets/d/ra-mp-6',
                statusRA: 'На доработку',
                statusClient: 'На доработку',
                createdAt: '2026-11-05',
                lastUploadedAt: '2026-11-12',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'p3',
    name: 'Весенняя активация 2027',
    clientId: 'c1',
    brandId: 'b1',
    settings: {
      period: {
        start: '2027-03-01',
        end: '2027-05-31',
      },
      approvalType: 'Строками',
      amountDisplay: 'Без НДС',
      orderParameters: {
        productionAsset: 'Актив 3',
        contractType: 'Основной',
        agencyLegalEntity: 'ООО РА Брусника',
        clientLegalEntity: 'ООО СберМаркет',
        contract: 'Договор №2027/SM-012',
      },
    },
    segments: [
      {
        id: 'seg-4',
        name: 'Москва',
        teamId: 'team-c1-moscow',
        mediaSegments: [
          {
            id: 'ms-6',
            mediaType: 'Outdoor',
            budget: 1800000,
            raDocumentUrl: 'https://docs.google.com/spreadsheets/d/ra-outdoor-2',
            clientDocumentUrl: 'https://docs.google.com/spreadsheets/d/client-outdoor-2',
            launchTasks: [],
            mediaPlans: [
              {
                id: 'mp-7',
                name: 'Весенние площадки',
                clientSheetUrl: 'https://docs.google.com/spreadsheets/d/client-mp-7',
                raSheetUrl: 'https://docs.google.com/spreadsheets/d/ra-mp-7',
                statusRA: 'В работе РА',
                statusClient: '—',
                createdAt: '2027-02-10',
                lastUploadedAt: '2027-02-15',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'p4',
    name: 'Летняя кампания СберБанк',
    clientId: 'c1',
    brandId: 'b2',
    settings: {
      period: {
        start: '2027-06-01',
        end: '2027-08-31',
      },
      approvalType: 'Документ',
      amountDisplay: 'С НДС',
      orderParameters: {
        productionAsset: 'Актив 4',
        contractType: 'Дополнительное соглашение',
        agencyLegalEntity: 'ООО РА Брусника',
        clientLegalEntity: 'ПАО Сбербанк',
        contract: 'ДС №15 к Договору №2026/SB-045',
      },
    },
    segments: [
      {
        id: 'seg-5',
        name: 'Всероссийский',
        teamId: 'team-c1-regions',
        mediaSegments: [
          {
            id: 'ms-7',
            mediaType: 'НСТ',
            budget: 2200000,
            raDocumentUrl: 'https://docs.google.com/spreadsheets/d/ra-nst-1',
            clientDocumentUrl: 'https://docs.google.com/spreadsheets/d/client-nst-1',
            launchTasks: [],
            mediaPlans: [
              {
                id: 'mp-8',
                name: 'НСТ размещение лето',
                clientSheetUrl: 'https://docs.google.com/spreadsheets/d/client-mp-8',
                raSheetUrl: 'https://docs.google.com/spreadsheets/d/ra-mp-8',
                statusRA: 'В работе у клиента',
                statusClient: 'Согласование',
                createdAt: '2027-05-20',
                lastUploadedAt: '2027-05-25',
              },
            ],
          },
          {
            id: 'ms-8',
            mediaType: 'Радио',
            budget: 1500000,
            raDocumentUrl: 'https://docs.google.com/spreadsheets/d/ra-radio-2',
            clientDocumentUrl: 'https://docs.google.com/spreadsheets/d/client-radio-2',
            launchTasks: [],
            mediaPlans: [],
          },
        ],
      },
    ],
  },
  {
    id: 'p11',
    name: 'Новогодняя кампания 2027',
    clientId: 'c1',
    brandId: 'b2',
    settings: {
      period: {
        start: '2026-12-15',
        end: '2027-01-15',
      },
      approvalType: 'Строками',
      amountDisplay: 'С НДС',
      orderParameters: {
        productionAsset: 'Актив NY-01',
        contractType: 'Основной',
        agencyLegalEntity: 'ООО РА Брусника',
        clientLegalEntity: 'ПАО Сбербанк',
        contract: 'Договор №2026/SB-NY-001',
      },
    },
    segments: [],
  },
  {
    id: 'p5',
    name: 'Яндекс.Маркет - Черная пятница 2026',
    clientId: 'c2',
    brandId: 'b3',
    settings: {
      period: {
        start: '2026-11-20',
        end: '2026-11-30',
      },
      approvalType: 'Строками',
      amountDisplay: 'С НДС',
      orderParameters: {
        productionAsset: 'Актив YM-1',
        contractType: 'Основной',
        agencyLegalEntity: 'ООО РА Брусника',
        clientLegalEntity: 'ООО Яндекс',
        contract: 'Договор №2026/YA-078',
      },
    },
    segments: [
      {
        id: 'seg-6',
        name: 'Москва и СПб',
        teamId: 'team-c2-digital',
        mediaSegments: [
          {
            id: 'ms-9',
            mediaType: 'Интернет',
            budget: 5500000,
            raDocumentUrl: 'https://docs.google.com/spreadsheets/d/ra-internet-2',
            clientDocumentUrl: 'https://docs.google.com/spreadsheets/d/client-internet-2',
            summarySheetUrl: 'https://docs.google.com/spreadsheets/d/summary-9',
            orderCode: '#628194',
            launchTasks: [
              { id: 'lt-7', period: 'Ноябрь 2026' },
            ],
            mediaPlans: [
              {
                id: 'mp-9',
                name: 'Programmatic кампания',
                clientSheetUrl: 'https://docs.google.com/spreadsheets/d/client-mp-9',
                raSheetUrl: 'https://docs.google.com/spreadsheets/d/ra-mp-9',
                statusRA: 'Согласовано',
                statusClient: 'Согласовано',
                createdAt: '2026-11-01',
                lastUploadedAt: '2026-11-05',
                confirmationTaskId: 'ct-2',
              },
              {
                id: 'mp-10',
                name: 'Социальные сети',
                clientSheetUrl: 'https://docs.google.com/spreadsheets/d/client-mp-10',
                raSheetUrl: 'https://docs.google.com/spreadsheets/d/ra-mp-10',
                statusRA: 'Согласовано',
                statusClient: 'Согласовано',
                createdAt: '2026-11-02',
                lastUploadedAt: '2026-11-06',
              },
            ],
          },
          {
            id: 'ms-10',
            mediaType: 'Outdoor',
            budget: 3200000,
            raDocumentUrl: 'https://docs.google.com/spreadsheets/d/ra-outdoor-3',
            clientDocumentUrl: 'https://docs.google.com/spreadsheets/d/client-outdoor-3',
            summarySheetUrl: 'https://docs.google.com/spreadsheets/d/summary-10',
            orderCode: '#739182',
            launchTasks: [],
            mediaPlans: [
              {
                id: 'mp-11',
                name: 'OOH метро и улицы',
                clientSheetUrl: 'https://docs.google.com/spreadsheets/d/client-mp-11',
                raSheetUrl: 'https://docs.google.com/spreadsheets/d/ra-mp-11',
                statusRA: 'В работе у клиента',
                statusClient: 'Согласование',
                createdAt: '2026-10-28',
                lastUploadedAt: '2026-11-03',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'p6',
    name: 'Яндекс - Продвижение новых сервисов',
    clientId: 'c2',
    brandId: 'b3',
    settings: {
      period: {
        start: '2027-01-15',
        end: '2027-03-31',
      },
      approvalType: 'Документ',
      amountDisplay: 'Без НДС',
      orderParameters: {
        productionAsset: 'Актив YM-2',
        contractType: 'Основной',
        agencyLegalEntity: 'ООО РА Брусника',
        clientLegalEntity: 'ООО Яндекс',
        contract: 'Договор №2027/YA-015',
      },
    },
    segments: [
      {
        id: 'seg-7',
        name: 'Федеральный',
        teamId: 'team-c2-tv',
        mediaSegments: [
          {
            id: 'ms-11',
            mediaType: 'ТВ',
            budget: 6800000,
            raDocumentUrl: 'https://docs.google.com/spreadsheets/d/ra-tv-3',
            clientDocumentUrl: 'https://docs.google.com/spreadsheets/d/client-tv-3',
            launchTasks: [],
            mediaPlans: [
              {
                id: 'mp-12',
                name: 'ТВ федеральные каналы',
                clientSheetUrl: 'https://docs.google.com/spreadsheets/d/client-mp-12',
                raSheetUrl: 'https://docs.google.com/spreadsheets/d/ra-mp-12',
                statusRA: 'Отказ',
                statusClient: 'Отказ',
                createdAt: '2027-01-05',
                lastUploadedAt: '2027-01-10',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'p7',
    name: 'Яндекс.Маркет Q2 2027',
    clientId: 'c2',
    brandId: 'b3',
    settings: {
      period: {
        start: '2027-04-01',
        end: '2027-06-30',
      },
      approvalType: 'Строками',
      amountDisplay: 'С НДС',
      orderParameters: {
        productionAsset: 'Актив YM-3',
        contractType: 'Рамочный',
        agencyLegalEntity: 'ООО РА Брусника',
        clientLegalEntity: 'ООО Яндекс',
        contract: 'Договор №2027/YA-042',
      },
    },
    segments: [
      {
        id: 'seg-8',
        name: 'Крупные города',
        teamId: 'team-c2-digital',
        mediaSegments: [
          {
            id: 'ms-12',
            mediaType: 'Интернет',
            budget: 4200000,
            raDocumentUrl: 'https://docs.google.com/spreadsheets/d/ra-internet-3',
            clientDocumentUrl: 'https://docs.google.com/spreadsheets/d/client-internet-3',
            summarySheetUrl: 'https://docs.google.com/spreadsheets/d/summary-12',
            launchTasks: [],
            mediaPlans: [
              {
                id: 'mp-13',
                name: 'Digital Q2',
                clientSheetUrl: 'https://docs.google.com/spreadsheets/d/client-mp-13',
                raSheetUrl: 'https://docs.google.com/spreadsheets/d/ra-mp-13',
                statusRA: 'В работе РА',
                statusClient: '—',
                createdAt: '2027-03-20',
                lastUploadedAt: '2027-03-20',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'p8',
    name: 'МТС Банк - Кредитные продукты 2026',
    clientId: 'c3',
    brandId: 'b4',
    settings: {
      period: {
        start: '2026-10-01',
        end: '2026-12-31',
      },
      approvalType: 'Документ',
      amountDisplay: 'С НДС',
      orderParameters: {
        productionAsset: 'Актив MB-1',
        contractType: 'Основной',
        agencyLegalEntity: 'ООО РА Брусника',
        clientLegalEntity: 'ООО МТС-Банк',
        contract: 'Договор №2026/MTSB-089',
      },
    },
    segments: [
      {
        id: 'seg-9',
        name: 'Москва',
        teamId: 'team-c3-moscow',
        mediaSegments: [
          {
            id: 'ms-13',
            mediaType: 'Outdoor',
            budget: 2800000,
            raDocumentUrl: 'https://docs.google.com/spreadsheets/d/ra-outdoor-4',
            clientDocumentUrl: 'https://docs.google.com/spreadsheets/d/client-outdoor-4',
            summarySheetUrl: 'https://docs.google.com/spreadsheets/d/summary-13',
            orderCode: '#928174',
            launchTasks: [
              { id: 'lt-10', period: 'Октябрь 2026' },
            ],
            mediaPlans: [
              {
                id: 'mp-14',
                name: 'OOH метро Москва',
                clientSheetUrl: 'https://docs.google.com/spreadsheets/d/client-mp-14',
                raSheetUrl: 'https://docs.google.com/spreadsheets/d/ra-mp-14',
                statusRA: 'На доработку',
                statusClient: 'На доработку',
                createdAt: '2026-09-15',
                lastUploadedAt: '2026-09-20',
              },
            ],
          },
          {
            id: 'ms-14',
            mediaType: 'Радио',
            budget: 1600000,
            raDocumentUrl: 'https://docs.google.com/spreadsheets/d/ra-radio-3',
            clientDocumentUrl: 'https://docs.google.com/spreadsheets/d/client-radio-3',
            summarySheetUrl: 'https://docs.google.com/spreadsheets/d/summary-14',
            orderCode: '#192837',
            launchTasks: [],
            mediaPlans: [
              {
                id: 'mp-15',
                name: 'Радио Москва FM',
                clientSheetUrl: 'https://docs.google.com/spreadsheets/d/client-mp-15',
                raSheetUrl: 'https://docs.google.com/spreadsheets/d/ra-mp-15',
                statusRA: 'На доработку',
                statusClient: 'На доработку',
                createdAt: '2026-09-18',
                lastUploadedAt: '2026-09-22',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'p9',
    name: 'МТС - Мобильная связь 2027',
    clientId: 'c3',
    brandId: 'b4',
    settings: {
      period: {
        start: '2027-02-01',
        end: '2027-04-30',
      },
      approvalType: 'Строками',
      amountDisplay: 'Без НДС',
      orderParameters: {
        productionAsset: 'Актив MTS-1',
        contractType: 'Основной',
        agencyLegalEntity: 'ООО РА Брусника',
        clientLegalEntity: 'ПАО МТС',
        contract: 'Договор №2027/MTS-024',
      },
    },
    segments: [
      {
        id: 'seg-10',
        name: 'Регионы ЦФО',
        teamId: 'team-c3-regional-tv',
        mediaSegments: [
          {
            id: 'ms-15',
            mediaType: 'ТВ',
            budget: 5200000,
            raDocumentUrl: 'https://docs.google.com/spreadsheets/d/ra-tv-4',
            clientDocumentUrl: 'https://docs.google.com/spreadsheets/d/client-tv-4',
            summarySheetUrl: 'https://docs.google.com/spreadsheets/d/summary-15',
            orderCode: '#283746',
            launchTasks: [
              { id: 'lt-11', period: 'Февраль 2027' },
              { id: 'lt-12', period: 'Март 2027' },
            ],
            mediaPlans: [
              {
                id: 'mp-16',
                name: 'ТВ региональные каналы',
                clientSheetUrl: 'https://docs.google.com/spreadsheets/d/client-mp-16',
                raSheetUrl: 'https://docs.google.com/spreadsheets/d/ra-mp-16',
                statusRA: 'Согласовано',
                statusClient: 'Согласовано',
                createdAt: '2027-01-20',
                lastUploadedAt: '2027-01-25',
                confirmationTaskId: 'ct-3',
              },
            ],
          },
          {
            id: 'ms-16',
            mediaType: 'НСТ',
            budget: 1900000,
            raDocumentUrl: 'https://docs.google.com/spreadsheets/d/ra-nst-2',
            clientDocumentUrl: 'https://docs.google.com/spreadsheets/d/client-nst-2',
            summarySheetUrl: 'https://docs.google.com/spreadsheets/d/summary-16',
            launchTasks: [],
            mediaPlans: [
              {
                id: 'mp-17',
                name: 'НСТ размещение регионы',
                clientSheetUrl: 'https://docs.google.com/spreadsheets/d/client-mp-17',
                raSheetUrl: 'https://docs.google.com/spreadsheets/d/ra-mp-17',
                statusRA: 'В работе у клиента',
                statusClient: 'Согласование',
                createdAt: '2027-01-22',
                lastUploadedAt: '2027-01-28',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'p10',
    name: 'МТС - Летние тарифы 2027',
    clientId: 'c3',
    brandId: 'b4',
    settings: {
      period: {
        start: '2027-05-15',
        end: '2027-08-15',
      },
      approvalType: 'Документ',
      amountDisplay: 'С НДС',
      orderParameters: {
        productionAsset: 'Актив MTS-2',
        contractType: 'Дополнительное соглашение',
        agencyLegalEntity: 'ООО РА Брусника',
        clientLegalEntity: 'ПАО МТС',
        contract: 'ДС №8 к Договору №2027/MTS-024',
      },
    },
    segments: [
      {
        id: 'seg-11',
        name: 'Федеральный + регионы',
        teamId: 'team-c3-multi',
        mediaSegments: [
          {
            id: 'ms-17',
            mediaType: 'Интернет',
            budget: 6500000,
            raDocumentUrl: 'https://docs.google.com/spreadsheets/d/ra-internet-4',
            clientDocumentUrl: 'https://docs.google.com/spreadsheets/d/client-internet-4',
            launchTasks: [],
            mediaPlans: [
              {
                id: 'mp-18',
                name: 'Digital летняя кампания',
                clientSheetUrl: 'https://docs.google.com/spreadsheets/d/client-mp-18',
                raSheetUrl: 'https://docs.google.com/spreadsheets/d/ra-mp-18',
                statusRA: 'Отказ',
                statusClient: 'Отказ',
                createdAt: '2027-05-01',
                lastUploadedAt: '2027-05-08',
              },
              {
                id: 'mp-19',
                name: 'Социальные сети лето',
                clientSheetUrl: 'https://docs.google.com/spreadsheets/d/client-mp-19',
                raSheetUrl: 'https://docs.google.com/spreadsheets/d/ra-mp-19',
                statusRA: 'В работе РА',
                statusClient: '—',
                createdAt: '2027-05-05',
                lastUploadedAt: '2027-05-10',
              },
            ],
          },
          {
            id: 'ms-18',
            mediaType: 'Outdoor',
            budget: 3800000,
            raDocumentUrl: 'https://docs.google.com/spreadsheets/d/ra-outdoor-5',
            clientDocumentUrl: 'https://docs.google.com/spreadsheets/d/client-outdoor-5',
            summarySheetUrl: 'https://docs.google.com/spreadsheets/d/summary-18',
            orderCode: '#485960',
            launchTasks: [],
            mediaPlans: [
              {
                id: 'mp-20',
                name: 'OOH федеральные города',
                clientSheetUrl: 'https://docs.google.com/spreadsheets/d/client-mp-20',
                raSheetUrl: 'https://docs.google.com/spreadsheets/d/ra-mp-20',
                statusRA: 'В работе РА',
                statusClient: '—',
                createdAt: '2027-05-03',
                lastUploadedAt: '2027-05-09',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'p12',
    name: 'Весенняя акция СберБанк 2027',
    clientId: 'c1',
    brandId: 'b2',
    settings: {
      period: {
        start: '2027-03-01',
        end: '2027-05-31',
      },
      approvalType: 'Строками',
      amountDisplay: 'С НДС',
      orderParameters: {
        productionAsset: 'Актив Spring-01',
        contractType: 'Основной',
        agencyLegalEntity: 'ООО РА Брусника',
        clientLegalEntity: 'ПАО Сбербанк',
        contract: 'Договор №2027/SB-SP-001',
      },
    },
    segments: [
      {
        id: 'seg-12',
        name: 'Федеральный канал',
        teamId: 'team-c1-shtab',
        mediaSegments: [
          {
            id: 'ms-21',
            mediaType: 'ТВ',
            budget: 8500000,
            raDocumentUrl: 'https://docs.google.com/spreadsheets/d/ra-tv-new',
            clientDocumentUrl: 'https://docs.google.com/spreadsheets/d/client-tv-new',
            summarySheetUrl: 'https://docs.google.com/spreadsheets/d/summary-19',
            launchTasks: [],
            mediaPlans: [
              {
                id: 'mp-21',
                name: 'Медиаплан ТВ Q1 2027',
                clientSheetUrl: 'https://docs.google.com/spreadsheets/d/client-mp-21',
                raSheetUrl: 'https://docs.google.com/spreadsheets/d/ra-mp-21',
                statusRA: 'В работе РА',
                statusClient: '—',
                createdAt: '2027-02-15',
                lastUploadedAt: '2027-02-20',
              },
              {
                id: 'mp-22',
                name: 'Медиаплан ТВ Q2 2027',
                clientSheetUrl: 'https://docs.google.com/spreadsheets/d/client-mp-22',
                raSheetUrl: 'https://docs.google.com/spreadsheets/d/ra-mp-22',
                statusRA: 'В работе у клиента',
                statusClient: 'Согласование',
                createdAt: '2027-02-18',
                lastUploadedAt: '2027-02-22',
              },
            ],
          },
          {
            id: 'ms-22',
            mediaType: 'Интернет',
            budget: 4200000,
            raDocumentUrl: 'https://docs.google.com/spreadsheets/d/ra-internet-new',
            clientDocumentUrl: 'https://docs.google.com/spreadsheets/d/client-internet-new',
            summarySheetUrl: 'https://docs.google.com/spreadsheets/d/summary-20',
            launchTasks: [],
            mediaPlans: [],
          },
        ],
      },
    ],
  },
];